export const STORAGE_KEYS = {
  mode: "iwd_mode_pref",
  theme: "iwd_theme_pref",
  template: "iwd_template_pref",
  language: "iwd_lang_pref",
  profile: "iwd_profile",
  music: "iwd_music_pref",
  analytics: "iwd_analytics",
};

export const DEFAULT_PROFILE = {
  employeeName: "",
  companyName: "",
  role: "",
  tone: "formal",
};

export const QUOTES = {
  en: [
    "Hard work is the foundation of success.",
    "Every worker builds the future.",
    "Respect every worker, respect every life.",
    "The dignity of work shapes great societies.",
    "Progress begins with daily discipline.",
    "Dedicated teams create lasting impact.",
    "Effort today becomes growth tomorrow.",
    "Pride in work leads to excellence.",
    "Strong organizations honor every role.",
    "Commitment is the engine of achievement.",
    "Work done with purpose transforms lives.",
  ],
  hi: [
    "मेहनत ही सफलता की सबसे मजबूत नींव है।",
    "हर कर्मचारी भविष्य का निर्माण करता है।",
    "हर श्रमिक का सम्मान, हर जीवन का सम्मान।",
    "अनुशासन और प्रयास से प्रगति बनती है।",
    "हर भूमिका संस्था को आगे बढ़ाती है।",
    "समर्पण से ही उत्कृष्टता जन्म लेती है।",
    "आज की मेहनत, कल की तरक्की है।",
    "काम में गर्व, जीवन में सम्मान।",
    "मिलकर काम करने से बड़ी उपलब्धियां मिलती हैं।",
    "निरंतर प्रयास ही परिवर्तन की ताकत है।",
    "ईमानदार श्रम समाज की असली शक्ति है।",
  ],
  hinglish: [
    "Hard work hi success ki asli foundation hai.",
    "Har employee future build karta hai.",
    "Har worker ka respect, har life ka respect.",
    "Daily discipline se real progress hoti hai.",
    "Dedicated teams long-term impact banati hain.",
    "Aaj ka effort kal ki growth deta hai.",
    "Work me pride rakhoge to excellence milegi.",
    "Har role company ko strong banata hai.",
    "Commitment hi achievement ka engine hai.",
    "Purpose ke saath kaam life change karta hai.",
    "Consistent mehnat se hi difference banta hai.",
  ],
};

export const SLOGANS = {
  en: ["Dignity at Work", "Work with Pride", "Respect Every Worker", "Build Together, Grow Together", "Effort Creates Impact"],
  hi: ["कार्य की गरिमा", "गर्व से काम करें", "हर कर्मचारी का सम्मान", "मिलकर बनाएं, साथ बढ़ें", "मेहनत से बदलाव"],
  hinglish: ["Dignity at Work", "Pride ke saath kaam", "Har worker ka respect", "Build saath me, Grow saath me", "Effort se impact"],
};

export const I18N = {
  en: {
    eyebrow: "May 1 | International Workers Day Wishes",
    installApp: "Install App",
    playMusic: "Play Music",
    pauseMusic: "Pause Music",
    replayConfetti: "Replay Confetti",
    liveDateTime: "Live Date & Time",
    engagement: "Engagement",
    wishesGenerated: "wishes generated",
    downloads: "downloads",
    language: "Language",
    personalization: "Advanced Personalization",
    employeeName: "Employee Name",
    companyName: "Company Name",
    roleOptional: "Role (optional)",
    smartGenerator: "Smart Wish Generator",
    chooseTone: "Choose Tone",
    generateWish: "Generate Wish",
    speakWish: "Speak Wish",
    themeAndLayout: "Theme & Template",
    themeLabel: "Theme",
    templateLabel: "Template",
    templateCard: "Card View",
    templateMinimal: "Minimal View",
    templateFestive: "Festive View",
    employeeAppreciation: "Employee Appreciation Message",
    workersDayWishesHeading: "International Workers Day Wishes",
    quoteTitle: "Motivational Thought",
    copyQuote: "Copy Quote",
    copied: "Copied",
    sloganTitle: "International Workers Day Slogans",
    actions: "Actions",
    downloadCard: "Download Card (PNG)",
    quickShare: "Quick Share",
    downloadMiniVideo: "Download Mini Frames",
  },
  hi: {
    eyebrow: "1 मई | अंतरराष्ट्रीय श्रमिक दिवस शुभकामनाएं",
    installApp: "ऐप इंस्टॉल करें",
    playMusic: "संगीत चलाएं",
    pauseMusic: "संगीत रोकें",
    replayConfetti: "कंफेटी दोबारा चलाएं",
    liveDateTime: "लाइव तारीख और समय",
    engagement: "एंगेजमेंट",
    wishesGenerated: "शुभकामनाएं जनरेट हुईं",
    downloads: "डाउनलोड",
    language: "भाषा",
    personalization: "उन्नत व्यक्तिगत संदेश",
    employeeName: "कर्मचारी का नाम",
    companyName: "कंपनी का नाम",
    roleOptional: "भूमिका (वैकल्पिक)",
    smartGenerator: "स्मार्ट विश जनरेटर",
    chooseTone: "टोन चुनें",
    generateWish: "विश जनरेट करें",
    speakWish: "विश सुनाएं",
    themeAndLayout: "थीम और टेम्पलेट",
    themeLabel: "थीम",
    templateLabel: "टेम्पलेट",
    templateCard: "कार्ड दृश्य",
    templateMinimal: "मिनिमल दृश्य",
    templateFestive: "फेस्टिव दृश्य",
    employeeAppreciation: "कर्मचारी सम्मान संदेश",
    workersDayWishesHeading: "अंतरराष्ट्रीय श्रमिक दिवस शुभकामनाएं",
    quoteTitle: "प्रेरक विचार",
    copyQuote: "कोट कॉपी करें",
    copied: "कॉपी हो गया",
    sloganTitle: "अंतरराष्ट्रीय श्रमिक दिवस नारे",
    actions: "कार्रवाइयां",
    downloadCard: "कार्ड डाउनलोड करें (PNG)",
    quickShare: "त्वरित शेयर",
    downloadMiniVideo: "मिनी फ्रेम डाउनलोड",
  },
  hinglish: {
    eyebrow: "1 May | International Workers Day Wishes",
    installApp: "App Install karo",
    playMusic: "Music Play karo",
    pauseMusic: "Music Pause karo",
    replayConfetti: "Confetti Replay",
    liveDateTime: "Live Date & Time",
    engagement: "Engagement",
    wishesGenerated: "wishes generate hui",
    downloads: "downloads",
    language: "Language",
    personalization: "Advanced Personalization",
    employeeName: "Employee Name",
    companyName: "Company Name",
    roleOptional: "Role (optional)",
    smartGenerator: "Smart Wish Generator",
    chooseTone: "Tone choose karo",
    generateWish: "Wish Generate karo",
    speakWish: "Wish Sunao",
    themeAndLayout: "Theme & Template",
    themeLabel: "Theme",
    templateLabel: "Template",
    templateCard: "Card View",
    templateMinimal: "Minimal View",
    templateFestive: "Festive View",
    employeeAppreciation: "Employee Appreciation Message",
    workersDayWishesHeading: "International Workers Day Wishes",
    quoteTitle: "Motivational Thought",
    copyQuote: "Quote Copy",
    copied: "Copied",
    sloganTitle: "International Workers Day Slogans",
    actions: "Actions",
    downloadCard: "Card Download (PNG)",
    quickShare: "Quick Share",
    downloadMiniVideo: "Mini Frames Download",
  },
};

export const MESSAGE_TEMPLATES = {
  formal: {
    en: [
      "{greeting}, on International Workers Day Wishes, we recognize your disciplined contribution as {rolePart} at {company}.",
      "{greeting}, your consistent professionalism at {company} reflects responsibility and excellence that we deeply appreciate.",
      "{greeting}, your work at {company} as {rolePart} demonstrates commitment, integrity, and organizational strength.",
    ],
    hi: [
      "{greeting}, अंतरराष्ट्रीय श्रमिक दिवस शुभकामनाओं के अवसर पर हम {company} में {rolePart} के रूप में आपके योगदान का सम्मान करते हैं।",
      "{greeting}, {company} में आपका निरंतर पेशेवर योगदान हमारी प्रगति की मजबूत नींव है।",
      "{greeting}, {company} में आपकी निष्ठा और जिम्मेदारी संस्था की सफलता को नई ऊंचाई देती है।",
    ],
    hinglish: [
      "{greeting}, International Workers Day Wishes ke din hum {company} me {rolePart} ke roop me aapke disciplined contribution ko salute karte hain.",
      "{greeting}, {company} me aapki professionalism aur commitment hamari growth ko strong banati hai.",
      "{greeting}, aapka responsible work culture {company} ko consistently better banata hai.",
    ],
  },
  friendly: {
    en: [
      "{greeting}, thank you for bringing positivity and effort to {company} every day. You make the workplace better for everyone.",
      "{greeting}, your energy and support at {company} truly inspire the team. Wishing you a wonderful International Workers Day.",
      "{greeting}, the way you show up for the team at {company} means a lot. Warm wishes for International Workers Day.",
    ],
    hi: [
      "{greeting}, {company} में आपका उत्साह और सहयोग टीम के लिए प्रेरणा है। अंतरराष्ट्रीय श्रमिक दिवस की हार्दिक शुभकामनाएं।",
      "{greeting}, आपका हर दिन का प्रयास कार्यस्थल को बेहतर बनाता है। धन्यवाद और शुभकामनाएं।",
      "{greeting}, {company} में आपकी सकारात्मक ऊर्जा टीम को आगे बढ़ाती है। श्रमिक दिवस की शुभकामनाएं।",
    ],
    hinglish: [
      "{greeting}, aapki positive energy {company} me sabko motivate karti hai. International Workers Day Wishes.",
      "{greeting}, daily effort aur teamwork ke liye dil se thank you. Aap great ho.",
      "{greeting}, aapke support se workplace aur better banta hai. Best wishes always.",
    ],
  },
  motivational: {
    en: [
      "{greeting}, your work ethic at {company} proves that consistent effort creates extraordinary outcomes.",
      "{greeting}, each day you move {company} forward with purpose. Keep rising and keep inspiring.",
      "{greeting}, your commitment as {rolePart} proves that progress belongs to those who persevere.",
    ],
    hi: [
      "{greeting}, {company} में आपका परिश्रम साबित करता है कि निरंतर प्रयास से असाधारण परिणाम मिलते हैं।",
      "{greeting}, आप हर दिन उद्देश्य के साथ संस्था को आगे बढ़ाते हैं। ऐसे ही प्रेरित करते रहें।",
      "{greeting}, {rolePart} के रूप में आपकी निष्ठा दिखाती है कि प्रगति मेहनत से मिलती है।",
    ],
    hinglish: [
      "{greeting}, aapka work ethic dikhata hai ki consistent effort se extraordinary results aate hain.",
      "{greeting}, aap har din {company} ko purpose ke saath aage badhate ho. Keep inspiring.",
      "{greeting}, {rolePart} ke roop me aapka dedication real progress ka example hai.",
    ],
  },
  corporate: {
    en: [
      "{greeting}, your contribution enables {company} to deliver value, reliability, and long-term impact.",
      "{greeting}, your excellence strengthens {company}'s culture, standards, and performance.",
      "{greeting}, your role as {rolePart} directly supports key mission outcomes at {company}.",
    ],
    hi: [
      "{greeting}, आपका योगदान {company} की गुणवत्ता, विश्वसनीयता और दीर्घकालिक प्रभाव को मजबूत करता है।",
      "{greeting}, आपकी उत्कृष्टता {company} की संस्कृति और प्रदर्शन को नई दिशा देती है।",
      "{greeting}, {rolePart} के रूप में आपका कार्य हमारे लक्ष्यों को सशक्त बनाता है।",
    ],
    hinglish: [
      "{greeting}, aapka contribution {company} ko reliability aur long-term impact deliver karne me help karta hai.",
      "{greeting}, aapki excellence se company culture aur performance dono strong hote hain.",
      "{greeting}, {rolePart} ke roop me aap directly business goals support karte hain.",
    ],
  },
};
